[project]
name = "smsaback"
version = "0.1.0"
description = "Middleware para gerenciamento de logs e Endpoints"
authors = [
    {name = "Pedro Pereira", email = "consultor.pedropereira@t10.digital"},
]
dependencies = [
  "psycopg2-binary",
  "pymongo",
  "python-json-logger",
  "python-dotenv"
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=src --cov-report=term-missing"
testpaths = [
  "tests"
]
pythonpath = [
  "src"
]

[tool.pdm.dev-dependencies]
test = [
  "pytest",
  "pytest-cov"
]

[tool.pdm]
distribution = true
